version: "3.3"

services:
  database:
    image: mysql/mysql-server
    container_name: database-merchant
    command: --max_allowed_packet=32505856  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: merchant_service_db
      MYSQL_USER: vlad
      MYSQL_PASSWORD: vlad
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - type: bind
        source: ./docker-setup/init-databases.sql
        target: /docker-entrypoint-initdb.d/init-databases.sql

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "merchant"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafdrop:
    image: obsidiandynamics/kafdrop:3.8.1
    container_name: kafdrop
    depends_on:
      - zookeeper
      - kafka
    expose:
      - 9000
    ports:
      - 9000:9000
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKERCONNECT: kafka:29092